export function createShellRuntimeConfig(deps = {}) {
    const {
        AppState,
        MemoryHistoryDB,
        Logger,
        ErrorHandler,
        confirmAction,
        defaultSettings,
        worldbookView,
        updateSettingsUI,
        updateChapterRegexUI,
        handleProviderChange,
        ensureModalStyles,
        bindModalEvents,
        loadSavedSettings,
        loadCategoryLightSettings,
        loadCustomCategories,
        renderCategoriesList,
        renderDefaultWorldbookEntriesUI,
        checkAndRestoreState,
        setProcessingStatus,
        getGlobalSemaphore,
        buildModalHtml,
        initializeModalState,
        restoreModalData,
        restoreExistingState,
        bindModalBasicEventsUI,
        bindSettingEventsUI,
        bindCollapsePanelEventsUI,
        bindPromptEventsUI,
        bindMessageChainEventsUI,
        bindFileEventsUI,
        bindActionEventsUI,
        bindStreamEventsUI,
        bindExportEventsUI,
        EventDelegate,
        closeModal,
        showHelpModal,
        saveCurrentSettings,
        handleUseTavernApiChange,
        handleFetchModels,
        handleQuickTest,
        rechunkMemories,
        showAddCategoryModal,
        resetToDefaultCategories,
        showAddDefaultEntryModal,
        saveDefaultWorldbookEntriesUI,
        applyDefaultWorldbookEntries,
        showResultSection,
        testChapterRegex,
        renderMessageChainUI,
        handleFileSelect,
        handleClearFile,
        handleStartConversion,
        handleStopProcessing,
        handleRepairFailedMemories,
        showStartFromSelector,
        showProcessedResults,
        toggleMultiSelectMode,
        deleteSelectedMemories,
        updateMemoryQueueUI,
        showSearchModal,
        showReplaceModal,
        showHistoryView,
        showConsolidateCategorySelector,
        showCleanTagsModal,
        showAliasMergeUI,
        showTxtConverterPanel,
        showStoryOutlinePanel,
        showCurrentChapterPanel,
        updateStreamContent,
        showPromptPreview,
        showPlotOutlineConfigModal,
        importAndMergeWorldbook,
        loadTaskState,
        saveTaskState,
        exportSettings,
        importSettings,
        exportCharacterCard,
        exportVolumes,
        exportToSillyTavern,
        showMemoryContentModal,
        updateStartButtonState,
        showQueueSection,
        showProgressSection,
        onEntryConfigChanged,
        onHashFallback,
    } = deps;

    return {
        AppState,
        MemoryHistoryDB,
        Logger,
        ErrorHandler,
        confirmAction,
        defaultSettings,
        createWorldbookView: () => worldbookView,
        worldbookViewDeps: {},
        createSettingsPersistenceServiceDeps: {
            updateSettingsUI,
            updateChapterRegexUI,
            handleProviderChange,
        },
        createModalLifecycleDeps: {
            addModalStyles: ensureModalStyles,
            bindModalEvents,
            loadSavedSettings,
            loadCategoryLightSettings,
            loadCustomCategories,
            renderCategoriesList,
            renderDefaultWorldbookEntriesUI,
            checkAndRestoreState,
        },
        createModalControllerDeps: {
            setProcessingStatus,
            getGlobalSemaphore,
            removeEscListener: (handler) => document.removeEventListener('keydown', handler, true),
            buildModalHtml,
            initializeModalState,
            restoreModalData,
            restoreExistingState,
            onRestoreStateError: (error) => Logger.error('State', '恢复状态失败:', error),
        },
        createModalEventBinderDeps: (createdModalController) => ({
            bindModalBasicEventsUI,
            bindSettingEventsUI,
            bindCollapsePanelEventsUI,
            bindPromptEventsUI,
            bindMessageChainEventsUI,
            bindFileEventsUI,
            bindActionEventsUI,
            bindStreamEventsUI,
            bindExportEventsUI,
            EventDelegate,
            AppState,
            ErrorHandler,
            closeModal,
            showHelpModal,
            getEscKeyHandler: () => createdModalController?.handleEscKey || (() => {}),
            saveCurrentSettings,
            handleUseTavernApiChange,
            handleProviderChange,
            handleFetchModels,
            handleQuickTest,
            rechunkMemories,
            showAddCategoryModal,
            confirmAction,
            resetToDefaultCategories,
            renderCategoriesList,
            showAddDefaultEntryModal,
            saveDefaultWorldbookEntriesUI,
            applyDefaultWorldbookEntries,
            showResultSection,
            updateWorldbookPreview: () => worldbookView.updateWorldbookPreview(),
            testChapterRegex,
            renderMessageChainUI,
            handleFileSelect,
            handleClearFile,
            handleStartConversion,
            handleStopProcessing,
            handleRepairFailedMemories,
            showStartFromSelector,
            showProcessedResults,
            toggleMultiSelectMode,
            deleteSelectedMemories,
            updateMemoryQueueUI,
            showSearchModal,
            showReplaceModal,
            showWorldbookView: (...args) => worldbookView.showWorldbookView(...args),
            showHistoryView,
            showConsolidateCategorySelector,
            showCleanTagsModal,
            showAliasMergeUI,
            showTxtConverterPanel,
            showStoryOutlinePanel,
            showCurrentChapterPanel,
            updateStreamContent,
            showPromptPreview,
            showPlotOutlineConfigModal,
            importAndMergeWorldbook,
            loadTaskState,
            saveTaskState,
            exportSettings,
            importSettings,
            exportCharacterCard,
            exportVolumes,
            exportToSillyTavern,
            showMemoryContentModal,
        }),
        fileImportDeps: {
            updateMemoryQueueUI,
            updateStartButtonState,
            showQueueSection,
            showProgressSection,
            showResultSection,
            updateWorldbookPreview: () => worldbookView.updateWorldbookPreview(),
            applyDefaultWorldbookEntries,
            saveCurrentSettings,
        },
        categoryLightStorageKey: 'storyweaverTxtToWorldbookSettings',
        onEntryConfigChanged,
        onHashFallback,
    };
}
